commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -427,6 +427,7 @@ jobs:
       
 #
   cloudfront-update:
+    cloudfront-update:
     docker:
        - image: amazon/aws-cli
       # Docker image here that supports AWS CLI
@@ -436,7 +437,6 @@ jobs:
           name: Install dependencies
           command: |
             yum install -y curl tar gzip
-
       - run:
           name: store workflow ID befor updating cloudfront 
           command: |
@@ -447,7 +447,7 @@ jobs:
               curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" --request PUT --data ${OldWorkflowId} https://api.memstash.io/values/workflow_id
             else
               echo "No WorkflowID found"
-              return 1
+              
             fi           
       - run:
           name: Update cloudfront distribution
@@ -455,39 +455,40 @@ jobs:
             aws cloudformation deploy \
               --stack-name udapeople-cloudfront \
               --template-file .circleci/files/cloudfront.yml \
-              --region us-east-2 \
+              --region ap-south-1 \
               --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
               --tags project=Udapeople
               
       - revert-migrations
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
-      # Here's where you will add some code to rollback on failure  
-#
+      # Here's where you will add some code to rollback on failure
+      
+
   cleanup:
     docker:
       - image: amazon/aws-cli
     steps:
       # Checkout code from git
       - run:
-          name: Get old stack workflow id
+          name: Get old stack workflow id and delete the old s3 bucket and stacks 
           command: |
-            export OldWorkflowId=$(curl -H "token: 96c4ffbc-21de-4e0a-bdb2-b5a923731f3f" --request GET https://api.memstash.io/values/migration)
-            echo "Privious_workflow_id is ${OldWorkflowId}"
+            export OldWorkflowID=$(curl -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" --request GET https://api.memstash.io/values/workflow_id)
+            echo "Privious_workflow_id is ${OldWorkflowID}"
             export STACKS=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --stack-status-filter CREATE_COMPLETE --output text)
-            echo " Privious Stacks are ${STACKS}"
-      - run:
-          name: Remove old stacks and files
-          command: |
+            echo " All Stacks are ${STACKS}"
+            # deleting the old s3 bucket and stacks
             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
-              aws s3 rm s3://udapeople-${OldWorkflowId}/ --recursive
-              aws cloudformation delete-stack --stack-name front-end-${OldWorkflowId}
-              aws cloudformation delete-stack --stack-name back-end-${OldWorkflowId}
+              echo "starting operations for OldWorkflowID=${OldWorkflowID}"
+              aws s3 rm s3://udapeople-${OldWorkflowID} --recursive
+              aws cloudformation delete-stack --stack-name front-end-${OldWorkflowID}
+              aws cloudformation delete-stack --stack-name back-end-${OldWorkflowID}
             else
               echo "No stack deleted"
+              exit 1
             fi
-           
+            
 
 workflows:
   default:
